### PR TITLE
Adds .gitignore and clears cache

### PR DESCRIPTION
**Pull request by UnHumbleBen**
The files in `project`, `target`, and `test_run_dir` are updated every run anyways, so there is no point in committing these.

### CODE REVIEW

**Comment by powerjg** [comment]
Oops! Thanks for fixing this!

Could you use the .gitignore from here: https://github.com/jlpteaching/dinocpu/blob/master/.gitignore.

**Comment by UnHumbleBen** [comment]
@powerjg That .gitignore does not ignore `project/`. Do you want the .gitignore for this repo to ignore or not ignore `project/`?

**Comment by powerjg** [comment]
The files `project/build.properties` and `project/plugins.sbt` are actually important.

The `.gitignore` entry for `target` is enough to ignore all of the other files `project`.

**Comment by UnHumbleBen** [comment]
@powerjg done

**Review by powerjg — APPROVED** [review]
Don't forget to fill out the gradescope extra credit :)

**Pull request merged**
